Update pose estimator
GreenBlitz/Charrrged-Up-2023 pull request #16
Opened 2023-02-06 20:57 UTC by greenblitz4590

2023-02-07 16:02 UTC, roygold8 requested changes

2023-02-07 16:02 UTC, roygold8 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +    private boolean debugDash = true;
Probably this and all other debug functions should be removed or be in the dashboard subsystem (I think its better to remove)

2023-02-10 12:46 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
>      public static final double translationKp = 2;
finals are UPPER_SNAKE_CASE

2023-02-10 12:46 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
>      private double tolerance = 0.05;
finals are UPPER_SNAKE_CASE

2023-02-10 12:46 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
>          if(debugDash) { this.debugDashboard(xCalc, yCalc, rotationCalc); }
If you use one liners don't use {}, but even better, don't do it as a one liner.

2023-02-10 12:46 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
>          return super.isFinished() || (xController.atGoal() && yController.atGoal() && rotationController.atGoal());
Raz - I'm not sure I'm correct, but do we need to call super.isFinished();

2023-02-10 15:13 UTC, merged