Pose exp comp
GreenBlitz/Charrrged-Up-2023 pull request #22
Opened 2023-02-12 16:57 UTC by greenblitz4590

sorry );

2023-02-12 19:45 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/RobotMap.java
> +		public final static double ITERATION_DT	= 0.021;
Broder - why not 0.02?

2023-02-12 19:45 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/RobotMap.java
> +			public static final PIDObject angPID = new PIDObject().withKp(0.4).withMaxPower(1.0);
y?

2023-02-12 19:45 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/subsystems/Limelight.java
>  public class Limelight extends GBSubsystem {
broder - check if this is right

2023-02-12 19:45 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/subsystems/swerve/SwerveChassis.java
> +                    Thread.sleep(20);
Use the const you set

2023-02-12 21:09 UTC, greenblitz4590 commented
dont merge without consulting asaf

2023-02-16 22:39 UTC, roygold8 requested changes

2023-02-16 22:39 UTC, roygold8 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +package edu.greenblitz.tobyDetermined.commands.swerve;
No. We wont have MoveToPos and MoveToPose

2023-02-16 22:39 UTC, roygold8 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +    public static final double rotKp = 2;
Why all of those not in robot map?

2023-02-16 22:39 UTC, roygold8 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +    public void debugDashboard(double xCalc, double yCalc, double rotationCalc){
probably should remove

2023-02-17 15:27 UTC, closed without merging