Auto teleop
GreenBlitz/Charrrged-Up-2023 pull request #6
Opened 2023-01-20 15:35 UTC by greenblitz4590

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +        xController = new ProfiledPIDController(2,0,0,RobotMap.Swerve.Autonomus.constraints);
What is 2?

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +//        SDS
Why is there commented code in the code?

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +        xController.setTolerance(0.2);
What is 0.2?

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +        xController = new ProfiledPIDController(2,0,0,RobotMap.Swerve.Autonomus.constraints);
(and following numbers)

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +        xController.setTolerance(0.2);
(and following numbers)

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +/*
Again, commented code

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/measurement/MoveAngularByJoystick.java
>  			return;
using return like this is the same as using break

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/measurement/MoveAngularByJoystick.java
>  			return;
Also, in this case it will cause inacurrate logs

2023-01-20 15:42 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/subsystems/swerve/SwerveChassis.java
> +		/*if (Limelight.getInstance().FindTarget()) {
commented code

2023-01-22 08:06 UTC, roygold8 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +package edu.greenblitz.tobyDetermined.commands.swerve;
Should be better structured for both modules and NO MAGIC NUMBERS.

2023-01-27 08:58 UTC, roygold8 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/measurement/MoveAngularByJoystick.java
> +		if (timer.advanceIfElapsed(TIME_TO_ACCELERATE)) {
Doc

2023-01-27 13:59 UTC, greenblitz4590 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +        xController.setTolerance(0.2); //magic number and proud
Broder - you shouldn't be proud, put this in const (translation tolerance + rotation tolerance)

2023-01-27 14:06 UTC, greenblitz4590 commented on src/main/deploy/pathplanner/90 degrees.path
> +{
delete file

2023-01-27 14:06 UTC, greenblitz4590 commented on src/main/deploy/pathplanner/generatedJSON/90 degrees.wpilib.json
> +[{"time":0.0,"pose":{"rotation":{"radians":0.0},"translation":{"x":4.0,"y":4.0}},"velocity":0,"acceleration":3.0,"curvature":0,"holonomicRotation":0.0,"angularVelocity":0.0,"holonomicAngularVelocity"
delete

2023-01-27 14:26 UTC, tnrz135 requested changes

2023-01-27 14:26 UTC, tnrz135 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +        double xCal = xController.atGoal() ? 0 : xController.calculate(SwerveChassis.getInstance().getRobotPose().getX());
what is xCal? (and yCal, rotationCal)

2023-01-31 06:14 UTC, roygold8 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +        SmartDashboard.putBoolean("at goal x",xController.atGoal());
probably all dashboard numbers are for debugging - should be removed / commented out / with debug flag

2023-01-31 06:15 UTC, roygold8 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/swerve/MoveToPos.java
> +    public MoveToPos(Pose2d pos) {
Best Practice to add command summary (Get to a location with 3 pid controllers...)

2023-01-31 17:02 UTC, merged