noam - added break coast toggle switch on robot (i saw 2910 behind th…
GreenBlitz/Charrrged-Up-2023 pull request #78
Opened 2023-05-23 16:57 UTC by greenblitz4590

…e glass or something)

2023-07-15 21:59 UTC, NoamRosenberg08 requested changes

2023-07-15 21:59 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/tobyDetermined/Robot.java
> +		SmartDashboard.putBoolean("switch state",BreakCoastSwitch.getInstance().isSwitchPressed());
make more space and make at another chunk

2023-07-15 21:59 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/tobyDetermined/RobotMap.java
> +    public static final int BREAK_COAST_SWITCH_DIO_PORT = 0;
make inside of a class

2023-07-15 21:59 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/utils/BreakCoastSwitch.java
> +package edu.greenblitz.utils;
Ctrl + Alt + L the shit out of it

2023-07-17 19:00 UTC, tnrz135 requested changes

2023-07-17 19:29 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/tobyDetermined/RobotMap.java
> +        public static final int BREAK_COAST_SWITCH_DIO_PORT = 0;
the port is acctually 0

2023-07-17 20:02 UTC, merged