Clawclaw
GreenBlitz/Charrrged-Up-2023 pull request #84
Opened 2023-10-11 13:35 UTC by YHerm

2023-10-11 16:36 UTC, NoamRosenberg08 requested changes

2023-10-11 16:36 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/NodeBase.java
> +    private  final double TOLERANCE_ANGLE = Units.degreesToRadians(3);
Ctrl + Alt + L this file

2023-10-11 16:36 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/NodeBase.java
as well, change to Claw state

2023-10-11 16:36 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/NodeToNeighbourSupplier.java
> +        SmartDashboard.putString("end node", String.valueOf(end));
move to arm debug dashboard

2023-10-11 16:36 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/tobyDetermined/subsystems/Dashboard.java
> +		armTab.addString("Current Node ID", () -> String.valueOf(NodeBase.getInstance().getCurrentNode()));
change dashboard display name (from current node id)

2023-10-11 16:36 UTC, NoamRosenberg08 commented on src/main/java/edu/greenblitz/tobyDetermined/subsystems/Dashboard.java
> +		armTab.addString("Current Node ID", () -> String.valueOf(NodeBase.getInstance().getCurrentNode()));
change from String.valueOf() to .toString()

2023-10-11 16:54 UTC, YHerm commented on src/main/java/edu/greenblitz/tobyDetermined/commands/NodeToNeighbourSupplier.java
> +        SmartDashboard.putString("end node", String.valueOf(end));
what where when how

2023-11-09 19:58 UTC, closed without merging

2023-11-09 19:58 UTC, NoamRosenberg08 commented
no need anymore