Node generic 2
GreenBlitz/Charrrged-Up-2023 pull request #87
Opened 2023-10-30 18:29 UTC by YHerm

2023-12-08 11:32 UTC, bossyshrimp68 reviewed
i dont know if it saves if i leave it open so ill finish my review and continue later🤙​

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MidNode.java
> +        gbNode = null;
why null?

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MidNode.java
> +    public GBNode getNodeArm() {
maybe change name to "getGbNode"

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MultiNodeSubsystem/AStarVertex.java
> +        for (int i = 0; i <= pathList.size() - 1; i++) {
same with the for below

```suggestion
        for (int i = 0; i < pathList.size(); i++) {
```

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MultiNodeSubsystem/AStarVertex.java
> +    public static void printPathVer(LinkedList<Vertex> pathList) {
does writing "vertex" really hurt?

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/commands/ArmCommand.java
delete file

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MultiNodeSubsystem/AStarVertex.java
> +    private static boolean ifNotInVerList(LinkedList<Vertex> verList, Vertex ver) {
just write vertex its 3 letters more, and no need for the if😍​

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MultiNodeSubsystem/AStarVertex.java
> +            Pair<Boolean, Double> a = returnIsVertexUsableAndCost(open.get(index), pathMap);
a like in asshole? or like in Armageddon

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MultiNodeSubsystem/AStarVertex.java
> +    public static Double getCostOfOtherSystemPathAndAddToMap(Vertex vertex, HashMap<Vertex, Pair<LinkedList<SystemsPos>, Double>> pathMap) {
split into two func

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MultiNodeSubsystem/AStarVertex.java
> +    public static Pair<LinkedList<SystemsPos>, Double> getPath(SystemsPos start, SystemsPos end, SystemsPos secondSystemPos) {
state the difference between get, return and return final path in the name or get good

2023-12-08 11:32 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MultiNodeSubsystem/AStarVertex.java
> +    public static void main(String[] args) {
the main shouldnt be here

2023-12-08 19:00 UTC, YHerm commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/MultiNodeSubsystem/AStarVertex.java
> +    public static void main(String[] args) {
it is

2023-12-10 17:08 UTC, bossyshrimp68 requested changes

2023-12-10 17:08 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/Nodesssss/NodeBase.java
> +    static {
YOAV

2023-12-11 22:36 UTC, bossyshrimp68 reviewed
good job!! ​😎​

2023-12-11 22:36 UTC, bossyshrimp68 commented on src/main/java/edu/greenblitz/tobyDetermined/subsystems/telescopicArm/Extender/SimulationExtender.java
> +        SmartDashboard.putNumber("simVoltage",appliedVoltage);
remove​❣️​

2023-12-16 16:54 UTC, closed without merging